name: bi-kd
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - certifi=2025.8.3
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudatoolkit-dev=11.7.0
  - cudnn=8.9.7.29
  - dataclasses=0.8
  - debugpy=1.8.12
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2025.7.0
  - fvcore=0.1.5.post20221221
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - idna=3.7
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtorch=2.1.2
  - libunistring=0.9.10
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nccl=2.27.3.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.6
  - portalocker=3.0.0
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch3d=0.7.6
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.8
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tabulate=0.9.0
  - tbb=2021.8.0
  - termcolor=2.1.0
  - tk=8.6.14
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - accelerate==0.34.2
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bitsandbytes==0.43.1
      - black==25.1.0
      - blinker==1.9.0
      - block-bootstrap-pytorch==0.1.6
      - bootstrap-pytorch==0.0.13
      - click==8.1.8
      - cloudpickle==3.1.1
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.1.3
      - dash==3.2.0
      - datasets==4.1.1
      - detectron2==0.6
      - dill==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - fonttools==4.59.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h5py==3.14.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iopath==0.1.9
      - ipdb==0.13.13
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lietorch==0.2
      - markdown==3.8.2
      - matplotlib==3.9.4
      - multidict==6.6.4
      - multiprocess==0.70.16
      - munch==4.0.0
      - mypy-extensions==1.1.0
      - narwhals==2.7.0
      - nbformat==5.10.4
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - panopticapi==0.1
      - pathspec==0.12.1
      - plotly==6.3.1
      - pretrainedmodels==0.7.4
      - propcache==0.4.0
      - protobuf==6.32.0
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2025.9.1
      - retrying==1.4.2
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.37.0
      - shapely==2.0.7
      - skipthoughts==0.0.1
      - smmap==5.0.2
      - submitit==1.5.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.9.16
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.3.1
      - transformers==4.45.2
      - triton==2.3.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.21.3
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.21.0
